config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope(
    '/articles',
    ['controller' => 'Articles'],
    function ($routes) {
        $routes->connect('/tagged/*', ['action' => 'tags']);
    }
);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Home', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Settings.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Settings Entity
 *
 * @property int $id
 * @property string $title
 * @property string $subtitle
 */
class Settings extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'title' => true,
        'subtitle' => true,
        'background_image' => true,
    ];

    protected function _getBackgroundImageUrl()
    {
        $image_path = "/files/Settings/background_image/{$this->background_image}";
        if (!file_exists(WWW_ROOT . $image_path)) {
            $image_path = '/img/home-bg.jpg';
        }

        return \Cake\Routing\Router::url($image_path);
    }
}

src/Template/Layout/admin.ctp
<?php
/**
 * @var \App\Model\Entity\Settings $settings
 */

$this->Form->setTemplates(\Cake\Core\Configure::read('FormTemplates.Admin'));
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?php echo $this->fetch('title'); ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->Html->css('lib/template/admin/vendor.css'); ?>
    <?php echo $this->Html->css('lib/template/admin/app.css'); ?>
    <?php echo $this->Html->css('lib/chosen.min.css'); ?>
    <?php echo $this->Html->css('admin.css'); ?>
    <?php echo $this->Html->meta('favicon.ico','img/favicon.ico',array('type' => 'icon')); ?>
</head>
<body>

<div class="main-wrapper">
    <div class="app" id="app">
        <header class="header">
            <div class="header-block header-block-collapse d-lg-none d-xl-none">
                <button class="collapse-btn" id="sidebar-collapse-btn">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <div class="header-block header-block-search">
            </div>
            <div class="header-block header-block-buttons">
            </div>
            <div class="header-block header-block-nav">
                <ul class="nav-profile">
                    <li class="profile dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="name"> <?= $this->request->getSession()->read('Auth.User.name'); ?></span>
                        </a>
                        <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                            <?= $this->Html->link(
                                '<i class="fa fa-user icon"></i> Profile',
                                ['controller' => 'users', 'action' => 'edit', $this->request->getSession()->read('Auth.User.id')],
                                ['class' => 'dropdown-item', 'escape' => false]
                            ) ?>
                            <?= $this->Html->link(
                                    '<i class="fa fa-power-off icon"></i> Logout',
                                    ['controller' => 'users', 'action' => 'logout'],
                                    ['class' => 'dropdown-item', 'escape' => false]
                            );?>
                        </div>
                    </li>
                </ul>
            </div>
        </header>
        <aside class="sidebar">
            <div class="sidebar-container">
                <div class="sidebar-header">
                    <div class="brand">
                        <?= $this->Html->link($settings->title, ['controller' => 'home']) ?>
                    </div>
                </div>
                <?= $this->element('Admin/menu'); ?>
            </div>
            <footer class="sidebar-footer">
            </footer>
        </aside>
        <div class="sidebar-mobile-menu-handle" id="sidebar-mobile-menu-handle"></div>
        <div class="mobile-menu-handle"></div>

        <article class="content dashboard-page">
            <?= $this->Flash->render(); ?>
            <?= $this->fetch('content'); ?>
        </article>
        <footer class="footer">
            <div class="footer-block">
                <?= $this->element('page-source') ?>
            </div>
        </footer>
    </div>
</div>


<?php echo $this->Html->script('lib/template/admin/vendor.js'); ?>
<?php echo $this->Html->script('lib/template/admin/app.js'); ?>
<?php echo $this->Html->script('lib/jquery.validate.min.js'); ?>
<?php echo $this->Html->script('lib/chosen.jquery.min.js'); ?>
<?php echo $this->Html->script('lib/tinymce/tinymce.min.js'); ?>
<?php echo $this->fetch('script'); ?>
<script>
    (function() {
        tinymce.init({
            selector: 'textarea',
            content_css: '../../../css/home.css',

            // Started with the full list of all plugins from https://www.tinymce.com/docs/demo/full-featured/, and then
            // removed ones which were unneeded for a relatively simplistic blog platform.
            plugins: 'fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media table anchor toc lists wordcount imagetools contextmenu colorpicker textpattern help',
            menubar: 'edit insert format table tools help',
            toolbar1: 'formatselect | bold italic strikethrough codetag | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat | fullpage',
            menu: {
                edit: {title: 'Edit', items: 'undo redo | cut copy paste | selectall'},
                insert: {title: 'Insert', items: 'link media'},
                format: {
                    title: 'Format',
                    items: 'bold italic underline strikethrough superscript subscript | formats | removeformat'
                },
                table: {title: 'Table', items: 'inserttable tableprops deletetable | cell row column'}
            },

            // This is quite messy, but the back story is that TinyMCE DOES provide the ability to format selected
            // text using <code></code> tags, but it does NOT allow you to put a button in the toolbar for this.
            // As such, I've hacked into the existing ability to toggle the 'code' style, based on the following
            // stack voerflow answer: https://stackoverflow.com/a/23241638. The "codetag" button is then used in the
            // "toolbar1" above.
            setup: function(editor) {
                editor.addButton('codetag', {
                    text: '',
                    icon: 'code',
                    onclick: function() {
                        editor.formatter.toggle('code');
                    }
                });
            },
        });

        $('select').chosen({width: '50%'});
    })();
</script>
</body>
</html>

src/Template/Layout/ajax.ctp
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @since         0.10.0
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

echo $this->fetch('content');

src/Template/Layout/auth.ctp
<?php
/**
 * @var \App\Model\Entity\Settings $settings
 */
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?php echo $this->fetch('title'); ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->Html->css('lib/template/admin/vendor.css'); ?>
    <?php echo $this->Html->css('lib/template/admin/app.css'); ?>
    <?php echo $this->Html->css('base.css'); ?>
    <?php echo $this->Html->css('admin.css'); ?>
</head>
<body>

<div class="auth">
    <div class="auth-container">
        <div class="card">
            <header class="auth-header">
                <h1 class="auth-title">
                    <?= $this->Html->link($settings->title, ['controller' => 'Home', 'action' => 'index']);?>
                </h1>
            </header>
            <div class="auth-content">

                <?= $this->Flash->render() ?>

                <?= $this->fetch('content') ?>

            </div>
        </div>
        <div class="text-center">
            <?= $this->Html->link('<i class="fa fa-arrow-left"></i> Home', ['controller' => 'Home', 'action' => 'index'], ['class' => 'btn btn-secondary btn-sm', 'escape' => false]); ?>
        </div>
    </div>
</div>

<?php echo $this->Html->script('lib/template/admin/vendor.js'); ?>
<?php echo $this->Html->script('lib/template/admin/app.js'); ?>
</body>
</html>

src/Template/Layout/customer.ctp
<?php
/**
 * @var \App\Model\Entity\Settings $settings
 */

$this->Form->setTemplates(\Cake\Core\Configure::read('FormTemplates.Admin'));
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?php echo $this->fetch('title'); ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->Html->css('lib/template/admin/vendor.css'); ?>
    <?php echo $this->Html->css('lib/template/admin/app.css'); ?>
    <?php echo $this->Html->css('lib/chosen.min.css'); ?>
    <?php echo $this->Html->css('admin.css'); ?>
</head>
<body>

<div class="main-wrapper">
    <div class="app" id="app">
        <header class="header">
            <div class="header-block header-block-collapse d-lg-none d-xl-none">
                <button class="collapse-btn" id="sidebar-collapse-btn">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <div class="header-block header-block-search">
            </div>
            <div class="header-block header-block-buttons">
            </div>
            <div class="header-block header-block-nav">
                <ul class="nav-profile">
                    <li class="profile dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="name"> <?= $this->request->getSession()->read('Auth.User.name'); ?></span>
                        </a>
                        <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                            <?= $this->Html->link(
                                    '<i class="fa fa-power-off icon"></i> Logout',
                                    ['controller' => 'users', 'action' => 'logout'],
                                    ['class' => 'dropdown-item', 'escape' => false]
                            );?>
                        </div>
                    </li>
                </ul>
            </div>
        </header>
        <aside class="sidebar">
            <div class="sidebar-container">
                <div class="sidebar-header">
                    <div class="brand">
                        <?= $this->Html->link($settings->title, ['controller' => 'home']) ?>
                    </div>
                </div>
                <?= $this->element('Customer/menu'); ?>
            </div>
            <footer class="sidebar-footer">
            </footer>
        </aside>
        <div class="sidebar-mobile-menu-handle" id="sidebar-mobile-menu-handle"></div>
        <div class="mobile-menu-handle"></div>

        <article class="content dashboard-page">
            <?= $this->Flash->render(); ?>
            <?= $this->fetch('content'); ?>
        </article>
        <footer class="footer">
            <div class="footer-block">
                <?= $this->element('page-source') ?>
            </div>
        </footer>
    </div>
</div>


<?php echo $this->Html->script('lib/template/admin/vendor.js'); ?>
<?php echo $this->Html->script('lib/template/admin/app.js'); ?>
<?php echo $this->Html->script('lib/jquery.validate.min.js'); ?>
<?php echo $this->Html->script('lib/chosen.jquery.min.js'); ?>
<?php echo $this->Html->script('lib/tinymce/tinymce.min.js'); ?>
<?php echo $this->fetch('script'); ?>

</body>
</html>

src/Template/Layout/default.ctp
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php echo $this->Html->meta('favicon.ico','img/favicon.ico',array('type' => 'icon')); ?>

    <title>IE CMS</title>

    <!-- Bootstrap core CSS -->
    <?= $this->Html->css('lib/bootstrap.min.css') ?>

    <!-- Custom fonts for this template -->
    <?= $this->Html->css('lib/font-awesome/css/fontawesome-all.min.css') ?>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <?= $this->Html->css('lib/template/public/clean-blog.min.css') ?>
    <?= $this->Html->css('home.css') ?>


</head>

<body>
<style>

</style>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <?= $this->Html->link('Home', ['controller' => 'home', 'action' => 'index'], ['class' => 'navbar-brand']) ?>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li id="search-wrapper" class="nav-item" style="display: none">
                    <?= $this->Form->create(null, ['url' => ['controller' => 'articles', 'action' => 'simpleSearch'], 'method' => 'GET']) ?>
                    <input class="search form-control" type="text" name="query" />
                    <?= $this->Form->end() ?>
                </li>
                <li class="nav-item">
                    <a id="search-show" class="nav-link" href="#">
                        <i class="fa fa-search"></i> Search
                    </a>
                </li>
                <li class="nav-item">
                    <a id="search-hide" class="nav-link" href="#" style="display: none">
                        <i class="fa fa-times"></i> Cancel
                    </a>
                </li>
                <?php if ($this->request->getSession()->read('Auth.User')) { ?>
                    <li class="nav-item">
                        <a>Welcome <?= $this->request->getSession()->read('Auth.User.name'); ?>!</a>
                    </li>
                <?php }?>
                <li class="dropdown nav-item">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" >
                        Store
                    </a>
                    <div class = "dropdown-menu">
                        <?= $this->Html->link(
                            'Store Home',
                            ['controller' => 'products', 'action' => 'storeIndex'],
                            ['class' => 'dropdown-item'])
                        ?>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Category Pages</a>
                        <a class="dropdown-item" href="#">Coming Soon</a>
                        <div style="text-align: center"><img src="https://i.imgur.com/9SYjjER.png" >
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <?= $this->Html->link(
                        'Send Enquiry',
                        ['controller' => 'enquiries', 'action' => 'add'],
                        ['class' => 'nav-link'])
                    ?>
                </li>
                <?php if ($this->request->getSession()->read('Auth.User')): ?>
                    <?php if ($this->request->getSession()->read('Auth.User.role') > 2 ) { ?>
                    <li class="nav-item">
                        <?= $this->Html->link('Dashboard', ['controller' => 'admin', 'action' => 'index'], ['class' => 'nav-link']) ?>
                    </li>
                    <?php } else { ?>
                    <li class="nav-item">
                        <?= $this->Html->link('Dashboard', ['controller' => 'customer', 'action' => 'index'], ['class' => 'nav-link']) ?>
                </li>
                    <?php }?>
                    <li class="nav-item">
                        <?= $this->Html->link(
                            'My Profile',
                            ['controller' => 'users', 'action' => 'edit', $this->request->getSession()->read('Auth.User.id')],
                            ['class' => 'nav-link'])
                        ?>
                    </li>
                    <li class="nav-item">
                        <?= $this->Html->link('Logout', ['controller' => 'users', 'action' => 'logout'], ['class' => 'nav-link']) ?>
                    </li>
                <?php else: ?>
                    <li class="nav-item">
                        <?= $this->Html->link('Login/ Register', ['controller' => 'users', 'action' => 'login', '?' => ['redirect' => '/admin']], ['class' => 'nav-link']) ?>
                    </li>
                <?php endif ?>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->
<header class="masthead" style="background-image: url('<?= $settings->background_image_url ?>')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="<?= $this->fetch('heading-class', 'page-heading') ?>">
                    <h1><?= $this->fetch('heading') ?></h1>
                    <?php if ($this->fetch('subheading')): ?>
                        <h2 class="subheading"><?= $this->fetch('subheading') ?></h2>
                    <?php endif ?>
                    <?php if ($this->fetch('meta')): ?>
                        <span class="meta"><?= $this->fetch('meta') ?></span>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-10 col-md-10 mx-auto">
            <?= $this->fetch('content') ?>
        </div>
    </div>
</div>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p class="copyright text-muted">
                    <?= $this->element('page-source') ?>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<?= $this->Html->script('lib/jquery-3.3.1.min.js') ?>
<?= $this->Html->script('lib/bootstrap.js') ?>

<!-- Custom scripts for this template -->
<?= $this->Html->script('lib/template/public/clean-blog.min.js') ?>

<?= $this->fetch('script') ?>

<script>
    (function() {
        var searchShow = $('#search-show');
        var searchHide = $('#search-hide');
        var searchWrapper = $('#search-wrapper');
        searchShow.click(function() {
            searchWrapper.show();
            searchHide.show();
            searchShow.hide();
            searchWrapper.find('input').focus();
        });
        searchHide.click(function() {
            searchWrapper.hide();
            searchHide.hide();
            searchShow.show();
            searchWrapper.find('input').blur();
        })
    })();
</script>

</body>

</html>

src/Template/Layout/store.ctp
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php echo $this->Html->meta('favicon.ico','img/favicon.ico',array('type' => 'icon')); ?>

    <title>IE CMS</title>

    <!-- Bootstrap core CSS -->
    <?= $this->Html->css('lib/bootstrap.min.css') ?>

    <!-- Custom fonts for this template -->
    <?= $this->Html->css('lib/font-awesome/css/fontawesome-all.min.css') ?>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <?= $this->Html->css('lib/template/public/clean-blog.min.css') ?>
    <?= $this->Html->css('home.css') ?>


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <?= $this->Html->link('Home', ['controller' => 'home', 'action' => 'index'], ['class' => 'navbar-brand']) ?>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li id="search-wrapper" class="nav-item" style="display: none">
                    <?= $this->Form->create(null, ['url' => ['controller' => 'articles', 'action' => 'simpleSearch'], 'method' => 'GET']) ?>
                    <input class="search form-control" type="text" name="query" />
                    <?= $this->Form->end() ?>
                </li>
                <li class="nav-item">
                    <a id="search-show" class="nav-link" href="#">
                        <i class="fa fa-search"></i> Search
                    </a>
                </li>
                <li class="nav-item">
                    <a id="search-hide" class="nav-link" href="#" style="display: none">
                        <i class="fa fa-times"></i> Cancel
                    </a>
                </li>
                <?php if ($this->request->getSession()->read('Auth.User')) { ?>
                    <li class="nav-item">
                        <a>Welcome <?= $this->request->getSession()->read('Auth.User.name'); ?>!</a>
                    </li>
                <?php }?>
                <li class="dropdown nav-item">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" >
                        Store
                    </a>
                    <div class = "dropdown-menu">
                        <?= $this->Html->link(
                            'Store Home',
                            ['controller' => 'products', 'action' => 'storeIndex'],
                            ['class' => 'dropdown-item'])
                        ?>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Category Pages</a>
                        <a class="dropdown-item" href="#">Coming Soon</a>
                        <div style="text-align: center"><img src="https://i.imgur.com/9SYjjER.png" >
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <?= $this->Html->link(
                        'Send Enquiry',
                        ['controller' => 'enquiries', 'action' => 'add'],
                        ['class' => 'nav-link'])
                    ?>
                </li>
                <?php if ($this->request->getSession()->read('Auth.User')): ?>
                    <?php if ($this->request->getSession()->read('Auth.User.role') > 2 ) { ?>
                    <li class="nav-item">
                        <?= $this->Html->link('Dashboard', ['controller' => 'admin', 'action' => 'index'], ['class' => 'nav-link']) ?>
                    </li>
                    <?php } else { ?>
                    <li class="nav-item">
                        <?= $this->Html->link('Dashboard', ['controller' => 'customer', 'action' => 'index'], ['class' => 'nav-link']) ?>
                </li>
                    <?php }?>
                    <li class="nav-item">
                        <?= $this->Html->link(
                            'My Profile',
                            ['controller' => 'users', 'action' => 'edit', $this->request->getSession()->read('Auth.User.id')],
                            ['class' => 'nav-link'])
                        ?>
                    </li>
                    <li class="nav-item">
                        <?= $this->Html->link('Logout', ['controller' => 'users', 'action' => 'logout'], ['class' => 'nav-link']) ?>
                    </li>
                <?php else: ?>
                    <li class="nav-item">
                        <?= $this->Html->link('Login/ Register', ['controller' => 'users', 'action' => 'login', '?' => ['redirect' => '/admin']], ['class' => 'nav-link']) ?>
                    </li>
                <?php endif ?>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->
<header class="masthead" style="background-image: url('<?= $settings->background_image_url ?>')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="<?= $this->fetch('heading-class', 'page-heading') ?>">
                    <h1>Store</h1>
                    <h2 class="subheading">We only supply the finest goods, the goods of Camelot!</h2>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-10 col-md-10 mx-auto">
            <?= $this->fetch('content') ?>
        </div>
    </div>
</div>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p class="copyright text-muted">
                    <?= $this->element('page-source') ?>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<?= $this->Html->script('lib/jquery-3.3.1.min.js') ?>
<?= $this->Html->script('lib/bootstrap.js') ?>

<!-- Custom scripts for this template -->
<?= $this->Html->script('lib/template/public/clean-blog.min.js') ?>

<?= $this->fetch('script') ?>

<script>
    (function() {
        var searchShow = $('#search-show');
        var searchHide = $('#search-hide');
        var searchWrapper = $('#search-wrapper');
        searchShow.click(function() {
            searchWrapper.show();
            searchHide.show();
            searchShow.hide();
            searchWrapper.find('input').focus();
        });
        searchHide.click(function() {
            searchWrapper.hide();
            searchHide.hide();
            searchShow.show();
            searchWrapper.find('input').blur();
        })
    })();
</script>

</body>

</html>